spring:
  h2:
    console:
      enabled: true
  profiles:
    active: h2
  datasource:
    url: jdbc:h2:mem:anagrafica
  main:
    log-startup-info: false
  liquibase:
    change-log: classpath:db/changelog-master.xml